name: cfclient
license: GPL-3.0
version: git
summary: Crazyflie client
description: |
  Crazyflie client
base: core18
confinement: strict
icon: snap/gui/cfclient.png

# Until we can use pyqt5 from apt, we are stuck to amd64 only
architectures:
  - build-on: amd64


parts:
  cfclient:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - libglu1-mesa
      - libxcb-glx0

apps:
  cfclient:
    command: python3 -m cfclient.gui
    extensions:
      - kde-neon
    plugs:
      - home
      - opengl
      - network
      - network-bind
      - raw-usb
      - joystick
